[package]
name = "oxifed"
readme = "README.md"
description = "A rabbitMQ based framework to run federated protocol services efficiently at scale"

version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
categories.workspace = true

[dependencies]
axum.workspace = true
axum-macros.workspace = true
chrono.workspace = true
clap.workspace = true
config.workspace = true
hyper.workspace = true
lapin.workspace = true
miette.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true

[workspace]
members = [
  "crates/*",
  "xtask",
]

[workspace.package]
version = "0.1.0-dev"
edition = "2021"
license = "GPL-3.0"
categories = ["servers", "activitypub", "rabbitmq", "email", "applications"]
homepage = "https://oxifed.openflowlabs.com/"
authors = ["Till Wegmüller <till.wegmueller@openflowlabs.com>"]
repository = "git@github.com:OpenFlowLabs/oxifed.git"
keywords = ["rabbitmq", "activitypub", "server", "email", "webfinger"]

[workspace.dependencies]
lapin = { version = "2.2.1", default-features = false, features = ["serde_json", "openssl"] }
deadpool-lapin = "0.10.0"
axum = { version = "0.6.18", features = ["tracing", "headers"] }
axum-macros = "0.3.7"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.4", features = ["derive"] }
config = "0.13.3"
miette = "5.9.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
thiserror = "1.0.40"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["json", "serde", "serde_json", "env-filter"] }
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.3.4", features = ["serde", "v4"] }
tokio = { version = "1.28.2", features = ["full"] }
tower = { version = "0.4.13", features = ["full", "tokio"] }
reqwest = {version="0.11.18", features= ["json"]}
hyper = { version = "0.14.26", features = ["full"] }
tower-http = { version = "0.4.1", features = ["tracing", "trace"] }
activitypub_federation = { version = "0.4.6", default-features = false, features = ["axum"] }
activitypub = {version ="0.1.0-dev", path = "crates/activitypub"}
oxilib = {version = "0.1.0-dev", path= "crates/oxilib"}
minio = { git = "https://github.com/minio/minio-rs.git", version = "0.1.0" }
biscuit-auth = { version = "3.2.0", features = ["serde", "uuid"] }
futures = "0.3.28"

[profile.dev.package.num-bigint-dig]
opt-level = 3
