version: '3.7'

services:
  mongodb:
    image: mongo:7
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/devkeyfile:/etc/devkeyfile"
      - "./mongodb/initdb:/docker-entrypoint-initdb.d/"
    command: --replSet rs0 --keyFile=/etc/devkeyfile --bind_ip 0.0.0.0
