version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_VHOST: "master"
      RABBITMQ_DEFAULT_USER: "dev"
      RABBITMQ_DEFAULT_PASS: "dev"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 8090:15672
      - 5672:5672

  minio:
    image: quay.io/minio/minio
    volumes:
      - minio:/data
    ports:
      - 9002:9000
      - 9003:9001
    command: ["server", "/data", "--console-address", ":9001"]

  couchdb:
    image: "couchdb"
    volumes:
      - couchdb:/opt/couchdb/data
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: dev
      COUCHDB_PASSWORD: dev

volumes:
  rabbitmq:
  minio:
  couchdb:
