name: images

on:
  push:
    branches:
      - 'main'
  release:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: openflowlabs/oxifed/identd:${{  github.ref_name }}
          file: crates/identd/Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: openflowlabs/oxifed/domainservd:${{  github.ref_name }}
          file: crates/domainservd/Dockerfile
