name: images

on:
  push:
    branches:
      - 'main'
  release:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["identd", "domainservd", "publisherd"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/openflowlabs/oxifed/${{ matrix.package }}:${{  github.ref_name }}
          build-args: "PACKAGE=${{ matrix.package }}"
